repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.21
    hooks:
      - id: uv-lock

  - repo: local
    hooks:
      - id: cp-readme
        name: Copy README.md to DOCS.md
        entry: cp hass-addon-control-group/README.md hass-addon-control-group/DOCS.md
        language: system
        pass_filenames: false

      - id: cp-readme-qsusb64
        name: Copy README.md to DOCS.md
        entry: cp hass-addon-qsusb64/README.md hass-addon-qsusb64/DOCS.md
        language: system
        pass_filenames: false

      - id: ruff-check
        name: ruff-check
        entry: uv run ruff check --fix --exit-non-zero-on-fix
        language: system
        pass_filenames: false

      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format --exit-non-zero-on-fix
        language: system
        pass_filenames: false

      - id: codespell
        name: codespell
        entry: uv run codespell --toml pyproject.toml
        language: system
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: uv run mypy --config-file pyproject.toml .
        language: system
        types: [python]
        pass_filenames: false
