---
name: Control group add-on
description: Add-on to manage and control groups of entities based on templates
version: "cc0cb01"
slug: hass-addon-control-group
image: ghcr.io/kellerza/hass-addon-control-group
url: https://github.com/kellerza/hass-addons
services: ["mqtt:need"]
hassio_api: true
hassio_role: homeassistant
homeassistant_api: true
init: false
apparmor: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - addon_config:rw
options:
  GROUPS:
    - ENTITIES: [light.my_light]
      TEMPLATE: "{{ iif(is_state('light.other', 'on'), 'on,light other', 'off') }}"
schema:
  GROUPS:
    - ENTITIES:
        - str
      TEMPLATE: str?
      NAME: str?

      TRIGGERS:
        - str?
  HA_PREFIX: str?
  UUID: str?

  HA_API_URL: str?
  HA_API_TOKEN: str?

  MQTT_HOST: str?
  MQTT_PORT: port?
  MQTT_USERNAME: str?
  MQTT_PASSWORD: password?

  DEBUG: int(0,5)?
