name: Deploy hass-addon-control-group addon to ghcr.io

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed
    paths:
      - ".github/workflows/deploy-control-group.yml"
      - "hass-addon-control-group/**"
      - "src/ha_addon_control_group/**"
      - "src/ha_addon/**"
  workflow_dispatch: {}

env:
  ADDON_SLUG: hass-addon-control-group
  ADDON_SLUG_EDGE: hass-addon-control-group
  PKG_NAME: ha_addon

jobs:
  call-deployer:
    uses: kellerza/hass-addons/.github/workflows/deployer.yml
    secrets: inherit
    with:
      addon-slug: ${{ env.ADDON_SLUG }}
      addon-slug-edge: ${{ env.ADDON_SLUG_EDGE }}
      pkg-name: ${{ env.PKG_NAME }}
      registry-image: ghcr.io/${{ github.repository_owner }}/${{ env.ADDON_SLUG }}
