name: Deploy hass-addon-control-group addon to ghcr.io

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    name: Test changed-files
    permissions:
      contents: write
      id-token: write
      packages: write
      pull-requests: read
    #secrets: inherit
    steps:
      - name: Get all test, doc and src files that have changed
        id: changed
        uses: tj-actions/changed-files@v47
        with:
          files: |
            - ".github/workflows/deploy-control-group.yml"
            - ".github/workflows/deployer2.yml"
            - "hass-addon-control-group/**"
            - "src/ha_addon_control_group/**"
            - "src/ha_addon/**"
    outputs:
      changed: ${{ steps.changed.outputs.any_changed }}

  deployer:
    if: deployer.outputs.changed == 'true'
    uses: kellerza/hass-addons/.github/workflows/deployer2.yml@main
    secrets: inherit
    with:
      app: hass-addon-control-group
      app-edge: hass-addon-control-group
      publish: true
    permissions:
      contents: write
      id-token: write
      packages: write
